part of 'theme.dart';

class Gaps {
  static const h4 = SizedBox(height: Sizes.p4);
  static const h8 = SizedBox(height: Sizes.p8);
  static const w8 = SizedBox(width: Sizes.p8);
  static const h16 = SizedBox(height: Sizes.p16);
  static const w16 = SizedBox(width: Sizes.p16);
  static const h24 = SizedBox(height: Sizes.p24);
  static const w24 = SizedBox(width: Sizes.p24);
  static const h32 = SizedBox(height: Sizes.p32);
  static const w32 = SizedBox(width: Sizes.p32);
  static const h40 = SizedBox(height: Sizes.p40);
  static const w40 = SizedBox(width: Sizes.p40);
  static const h48 = SizedBox(height: Sizes.p48);
  static const w48 = SizedBox(width: Sizes.p48);
  static const h56 = SizedBox(height: Sizes.p56);
  static const w56 = SizedBox(width: Sizes.p56);
  static const h64 = SizedBox(height: Sizes.p64);
  static const w64 = SizedBox(width: Sizes.p64);
  static const h72 = SizedBox(height: Sizes.p72);
  static const w72 = SizedBox(width: Sizes.p72);
  static const h80 = SizedBox(height: Sizes.p80);
  static const w80 = SizedBox(width: Sizes.p80);
  static const h88 = SizedBox(height: Sizes.p88);
  static const w88 = SizedBox(width: Sizes.p88);
  static const h96 = SizedBox(height: Sizes.p96);
  static const w96 = SizedBox(width: Sizes.p96);
  static const h104 = SizedBox(height: Sizes.p104);
  static const w104 = SizedBox(width: Sizes.p104);
  static const h112 = SizedBox(height: Sizes.p112);
  static const w112 = SizedBox(width: Sizes.p112);
  static const h120 = SizedBox(height: Sizes.p120);
  static const w120 = SizedBox(width: Sizes.p120);
  static const h128 = SizedBox(height: Sizes.p128);
  static const w128 = SizedBox(width: Sizes.p128);
  static const h136 = SizedBox(height: Sizes.p136);
  static const w136 = SizedBox(width: Sizes.p136);
  static const h144 = SizedBox(height: Sizes.p144);
  static const w144 = SizedBox(width: Sizes.p144);
  static const h152 = SizedBox(height: Sizes.p152);
  static const w152 = SizedBox(width: Sizes.p152);
  static const h160 = SizedBox(height: Sizes.p160);
  static const w160 = SizedBox(width: Sizes.p160);
  static const h168 = SizedBox(height: Sizes.p168);
  static const w168 = SizedBox(width: Sizes.p168);
  static const h176 = SizedBox(height: Sizes.p176);
  static const w176 = SizedBox(width: Sizes.p176);
  static const h184 = SizedBox(height: Sizes.p184);
  static const w184 = SizedBox(width: Sizes.p184);
  static const h192 = SizedBox(height: Sizes.p192);
  static const w192 = SizedBox(width: Sizes.p192);
  static const h200 = SizedBox(height: Sizes.p200);
  static const w200 = SizedBox(width: Sizes.p200);
  static const hInfinity = SizedBox(width: double.infinity);
  static const wInfinity = SizedBox(width: double.infinity);

  Gaps._();
}
